title: Grace Nguyen
email: nguyengrace@utexas.edu
description: Statistics and Data Science Student #ignores newlines until baseurl
github_username: gracenguyn

#build settings
theme: minima
plugins:
  - jekyll-feed
